version: 0.1

env:
  variables:
    TF_VERSION: "0.12.26"
phases:

  install:
    commands:
      # install required binary
      - "curl -s -qL -o /usr/bin/jq https://stedolan.github.io/jq/download/linux64/jq"
      - "chmod +x /usr/bin/jq"
      - "cd /usr/bin"
      - pwd
      - "curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/0.12.26/terraform_0.12.26_linux_amd64.zip"
      - ls terraform.zip
      - pwd
      - "unzip -o terraform.zip"
      - pwd
      - mv terraform /usr/bin/
      - "chmod +x /usr/bin/jq"
      - ls /usr/bin/terraform

  pre_build:
    commands:
      - export AWS_ACCESS_KEY_ID=$ACCESS_KEY_ID
      - export AWS_SECRET_ACCESS_KEY=$SECRET_ACCESS_KEY

  build:
    commands:
      - pwd
      - ls
      # - cd "$CODEBUILD_SRC_DIR"
      - echo " building"
      - /usr/bin/terraform init -no-color
      - /usr/bin/terraform plan -no-color
      - /usr/bin/terraform apply -no-color

  post_build:
    commands:
      - echo "terraform completed on `date`"


artifacts:
  files:
    - '**/*'
